export const GlobalActividades = [
    {
        id: 1,
        codmateria: '0253',
        materia: 'MIS ACTIVIDADES SIN ENVIAR',
        pendietes: '4',
        porcentaje: '5.27%',
        classe: 'text-success',
        observacion: 'Tiene Actividades por entregar',
        name: 'Danger',
        color: 'danger',
        selected: '2',
    },
    {
        id: 2,
        codmateria: '5012',
        materia: 'MIS ACTIVIDADES ENVIADAS',
        pendietes: '2',
        porcentaje: '100%',
        classe: 'text-success',
        observacion: 'Tiene Actividades por entregar',
        name: 'Success',
        color: 'success',
        selected: '2',
    },
    {
        id: 3,
        codmateria: '516',
        materia: 'MIS CURSOS',
        pendietes: '22',
        porcentaje: '27%',
        classe: 'text-success',
        observacion: 'Tiene Actividades por entregar',
        name: 'Warning',
        color: 'warning',
        selected: '2',
    },
    {
        id: 4,
        codmateria: '0513',
        materia: 'MIS VIDEOS DE CLASES',
        pendietes: '0',
        porcentaje: '0%',
        classe: 'text-warning',
        observacion: 'No tiene Actividades por entregar',
        name: 'Secondary',
        color: 'secondary',
        selected: '2',
    },
];