export const GlobalAsinaturas = [
    {
        id: 1,
        codmateria: '0252',
        materia: '0252-OPERACIONES DE PLANTA Y MAQUINARIA MINERAS',
        pendietes: '3',
        porcentaje: '4.27%',
        classe: 'text-success',
        observacion: 'Tiene Actividades por entregar',
        name: 'Primary',
        color: 'primary',
        selected: '2',
    },
    {
        id: 2,
        codmateria: '5011',
        materia: '5011-QUIMICA',
        pendietes: '1',
        porcentaje: '99%',
        classe: 'text-success',
        observacion: 'Tiene Actividades por entregar',
        name: 'Secondary',
        color: 'secondary',
        selected: '2',
    },
    {
        id: 3,
        codmateria: '515',
        materia: '515-MAQUINARIA Y EQUIPOS INDUSTRIALES',
        pendietes: '21',
        porcentaje: '26%',
        classe: 'text-success',
        observacion: 'Tiene Actividades por entregar',
        name: 'Danger',
        color: 'danger',
        selected: '2',
    },
    {
        id: 4,
        codmateria: '0512',
        materia: '0512-INVESTIGACION DE SEGURIDAD',
        pendietes: '-1',
        porcentaje: '-1%',
        classe: 'text-warning',
        observacion: 'No tiene Actividades por entregar',
        name: 'Success',
        color: 'success',
        selected: '2',
    },
    {
        id: 5,
        codmateria: '0516',
        materia: '0516-INGLES I',
        pendietes: '7',
        porcentaje: '56%',
        classe: 'text-success',
        observacion: 'Tiene Actividades por entregar',
        name: 'Warning',
        color: 'warning',
        selected: '2',
    },
];



